### ISSUE TITLE
Storybook example currently leads to a 404 error

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/react-link-to-inbox#11]
The storybook example in the Readme.md currently leads through a couple redirects that ultimately lead to a 404 error. We should update the storybook link to correctly display the example.

**Comment by hnarasaki** [comment]
I'd like to try this one!

**Comment by hnarasaki** [comment]
Created PR: https://github.com/indeedeng/react-link-to-inbox/pull/12

**Comment by hnarasaki** [comment]
Hi @DuaneOBrien, I created a PR, but the build failed. I looked into the error and thought maybe it's because I didn't have the right version of npm/yarn, so I upgraded and tried again, but the build still failed. Was wondering if you have any insight on how to fix it?

**Comment by loferris** [comment]
@DuaneOBrien Not sure if @hnarasaki  is still working on this one, but I can try to independently confirm the build is failing with the fix. To confirm, [is this](https://doug-wade.github.io/react-link-to-inbox/?selectedKind=LinkToInbox&selectedStory=simple%20example&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) where you want the link to go?
